### ISSUE TITLE
Does not trigger when the form starts with default data

### ISSUE THREAD

**Issue by robertocerdasilva** [razr001/ant-float-label#1]
Hi! this not working with Form.setFieldsValue
placeholder is displayed behind the input content.

```
useEffect(() => {
    form.setFieldsValue(values))
}, [values])
```

new post:
![image](https://github.com/razr001/ant-float-label/assets/72045538/6ce5e0a9-6883-47e5-a523-e4e41942b633)

edit post with data, placeholder is displayed behind the input content:
![image](https://github.com/razr001/ant-float-label/assets/72045538/8055a208-356c-4eb3-b0d7-2096c7eefb7a)

**Comment by razr001** [comment]
Fixed,please install v1.1.0
