### ISSUE TITLE
Is there any way for styling?

### ISSUE THREAD

**Issue by vylink** [razr001/ant-float-label#4]
Hi there,

thanks for fantastic work. Is there any way to style components for dark mode? I'd like to change a text colour for FloatInput's label for example.

Thank you for any advice :)

**Comment by razr001** [comment]
Sure. You can use antd [customize theme](https://ant-design.antgroup.com/docs/react/customize-theme). All props same as antd.
Thanks.

**Comment by vylink** [comment]
I see, but cannot find the right way to change colours of the custom components. Can you provide some very basic example of how to change border colour and label colour of FloatingInput, please?

**Comment by razr001** [comment]
You can try the codes
```
<ConfigProvider theme={{token: {colorPrimary: "#FF00CC"}  }}>
    <FloatInput placeholder="User Name" />
</ConfigProvider> 
```
