### ISSUE TITLE
useValueHandle value update issue

### ISSUE THREAD

**Issue by magicdawn** [razr001/ant-float-label#5]
reproduce link https://stackblitz.com/edit/antd-reproduce-5x-wpymec?file=demo.tsx

![01](https://github.com/user-attachments/assets/58f3a919-4088-4d03-8888-3b790c8fa65f)

value not synced in useValueHandle, https://github.com/razr001/ant-float-label/blob/fd02e5129cc2d72a4c75d02761fee40ee970b453/src/hook/useValueHandle.ts#L40-L48

**Comment by razr001** [comment]
Fixed. Please upgrade to v1.1.1
